import smtplib

def qna_confirm_mail(to, docid):
    # msg = "Subject : Confirmation of your question \n\nGreetings,\nThank you so much for registering for Master PraQ!\nBrain Rhyme presents you to Master PraQ, Practical Approach To Learning, a 2 day program, every Friday and Saturday from 8:30 pm to 9:30 pm IST where we will be giving you creative tips on different fields of work.\nThis Friday we have Ruth , an enthusiastic teacher and creator who is going to give us exciting Maths Tips.\nThis Saturday we have Shikha Bhattacharjee, a poet, content creator and an Entrepreneur from USA who will be talking about “Rational and Creative Thinking In Entrepreneurship”\nPlease find the links to the zoom sessions below:\n\n\nDay 1:\n\nJoin Zoom Meeting\nhttps://zoom.us/j/99921793442?pwd=NWdMMDNDT3MzUW9NM2FnYjd3NEQ4UT09\n\nMeeting ID: 999 2179 3442\n\nPasscode: masterpraq\n\n\nDay 2:\n\nJoin Zoom Meeting\nhttps://zoom.us/j/97696734686?pwd=c3BpVWZOdERLTnVkaDRvam52ZzFsUT09\n\nMeeting ID: 976 9673 4686\n\nPasscode: ZRkh3e\n\n\nYour registration id : "+docid+"\n\n\n\nLooking forward to seeing you all there!\nFor any further help/suggestion feel free to contact us at +918088117560"
    server = smtplib.SMTP('smtp.gmail.com',587)
    server.ehlo()
    server.starttls()
    server.login('brainrhymesingapore@gmail.com', 'Sushant@123') 
    server.sendmail('brainrhymesingapore@gmail.com', to, 'Subject : Confirmation of your question \n\nGreetings,\nThank you so much for registering for Master PraQ!\nBrain Rhyme presents you to Master PraQ, Practical Approach To Learning, a 2 day program, every Friday and Saturday from 8:30 pm to 9:30 pm IST where we will be giving you creative tips on different fields of work.\nThis Friday we have Ruth , an enthusiastic teacher and creator who is going to give us exciting Maths Tips.\nThis Saturday we have Shikha Bhattacharjee, a poet, content creator and an Entrepreneur from USA who will be talking about "Rational and Creative Thinking In Entrepreneurship"\nPlease find the links to the zoom sessions below:\n\n\nDay 1:\n\nJoin Zoom Meeting\nhttps://zoom.us/j/99921793442?pwd=NWdMMDNDT3MzUW9NM2FnYjd3NEQ4UT09\n\nMeeting ID: 999 2179 3442\n\nPasscode: masterpraq\n\n\nDay 2:\n\nJoin Zoom Meeting\nhttps://zoom.us/j/97696734686?pwd=c3BpVWZOdERLTnVkaDRvam52ZzFsUT09\n\nMeeting ID: 976 9673 4686\n\nPasscode: ZRkh3e\n\n\nYour registration id : '+docid+'  \n\n\n\nLooking forward to seeing you all there!\nFor any further help/suggestion feel free to contact us at +918088117560')
    server.close()
    print("Mail Sent!")
    return 1
